const English = {
    SectionsTabCoursesHeader: "Courses Section",
    SectionsTabButtonForAddSection: "Add New Section",
    SectionTabMessageNoCourses: "No sections available",
    SectionTabButtonAddContentToTheCourse: "Add content",
    SectionTabContentForNoContentInTheCourse: "No content in this section yet",
    SectionTabTextForNoSelectedSection: "Select a section to view its content",
    SectionTabForEmptyCourse: "Create First Section",

    SettingsTabCourseSettingsTitle: "Course Settings",
    SettingsTabCourseDescriptionLabel: "Course description",
    SettingsTabCourseNameLabel: "Course Name",
    SettingsTabSaveChangesButton: "Save Changes",
    SettingsTabSavingButton: "Saving...",
    SettingsTabSuccessMessage: "Changes saved successfully.",
    SettingsTabErrorMessage: "An error occurred while saving.",
    SettingsTabEnrollStudentTitle: "Enroll Student",
    SettingsTabStudentEmailLabel: "Student Email",
    SettingsTabEnrollStudentButton: "Enroll Student",
    SettingsTabEnrollSuccessMessage: "Student enrolled successfully.",
    SettingsTabEnrollErrorMessage: "Failed to enroll student.",
    SettingsTabExportButton: "Export Course",
    SettingsTabDeleteButton: "Delete Course",

    StudentsTabTitle: "Enrolled Students",
    StudentsTabNoStudentsMessage: "No students enrolled in this course",
    StudentsTabUnenroll: "Unenroll",
    StudentsTabUnenrolling: "Unenrolling...",
    StudentsTabModalTitle: "Student Card",
    StudentsTabModalFirstNameLabel: "First Name",
    StudentsTabModalLastNameLabel: "Last Name",
    StudentsTabModalEmailLabel: "Email",
    StudentsTabModalTableHeaderTest: "Test",
    StudentsTabModalTableHeaderGrade: "Grade",
    StudentsTabModalTest1: "Test 1",
    StudentsTabModalTest2: "Test 2",
    StudentsTabModalTest3: "Test 3",
    StudentsTabModalTest4: "Test 4",
    StudentsTabModalDropButton: "Drop student",
    StudentsTabModalCancelButton: "Cancel",
    StudentsTabModalSaveButton: "Save",

    AddCourseModalTitle: "Add New Course",
    AddCourseModalLabelName: "Course Name",
    AddCourseModalPlaceholderName: "Enter course name",
    AddCourseModalLabelDescription: "Description",
    AddCourseModalPlaceholderDescription: "Enter course description",
    AddCourseModalLabelColor: "Course Color",
    AddCourseModalButtonCancel: "Cancel",
    AddCourseModalButtonSubmit: "Add Course",
    AddCourseModalButtonSubmitting: "Adding...",

    AddLinkModalTitle: "Add Link",
    AddLinkModalLabelTitle: "Link Title",
    AddLinkModalPlaceholderTitle: "Enter link title",
    AddLinkModalLabelURL: "URL",
    AddLinkModalPlaceholderURL: "https://example.com",
    AddLinkModalLabelDescription: "Description (optional)",
    AddLinkModalPlaceholderDescription: "Enter link description",
    AddLinkModalButtonCancel: "Cancel",
    AddLinkModalButtonSubmit: "Add Link",
    AddLinkModalButtonSubmitting: "Adding...",

    QuizModalTitleAddStep1: "Add New Quiz",
    QuizModalTitleAddStep2: "Add Quiz Questions",
    QuizModalTitleEditStep1: "Edit Quiz Details",
    QuizModalTitleEditStep2: "Edit Quiz Questions",
    QuizModalLabelTitle: "Quiz Title",
    QuizModalPlaceholderTitle: "Enter quiz title",
    QuizModalLabelDescription: "Description",
    QuizModalPlaceholderDescription: "Enter quiz description (optional)",
    QuizModalLabelTimeLimit: "Time Limit (minutes)",
    QuizModalNoQuestions: 'No questions yet. Click "Add Question" to create your first question.',
    QuizModalQuestionText: "Question Text",
    QuizModalPoints: "Points",
    QuizModalOptionsLabel: "Options (select one as correct)",
    QuizModalAddOption: "Add Option",
    QuizModalAddQuestion: "Add Question",
    QuizModalButtonCancel: "Cancel",
    QuizModalButtonNext: "Next",
    QuizModalButtonSaving: "Saving...",
    QuizModalButtonSave: "Save Quiz",
    QuizModalButtonSaveChanges: "Save Changes",

    addSectionModalTitle: "Add New Section",
    addSectionModalLabelName: "Section Name",
    addSectionModalPlaceholderName: "Enter section name",
    addSectionModalButtonCancel: "Cancel",
    addSectionModalButtonSubmit: "Add Section",
    addSectionModalButtonSubmitting: "Adding...",

    UploadFileModalTitle: "Upload File",
    UploadFileModalSelectFile: "Select File",
    UploadFileModalDragAndDrop: "Click to select a file or drag and drop",
    UploadFileModalFileInfo: "Click to select a file",
    UploadFileModalError: "An error occurred while uploading.",
    UploadFileModalCancelButton: "Cancel",
    UploadFileModalSubmitButton: "Upload File",
    UploadFileModalUploadingButton: "Uploading...",


};
